export const Trigger = [
  'sheets',
  'google sheets',
  'spreadsheet',
  'spreadsheets',
  'sheet',
  'worksheet',
  'workbook',
  'grid',
  'rows',
  'columns',
  'cell',
  'cells',
  'range',
  'ranges',
  'data',
  'dataset',
  'table',
  'tables',
  'create sheet',
  'new sheet',
  'edit sheet',
  'update sheet',
  'delete sheet',
  'rename sheet',
  'duplicate sheet',
  'copy sheet',
  'move sheet',
  'add row',
  'add column',
  'delete row',
  'delete column',
  'insert row',
  'insert column',
  'sort',
  'filter',
  'filter view',
  'find',
  'find and replace',
  'formula',
  'formulas',
  'function',
  'functions',
  'sum',
  'average',
  'count',
  'min',
  'max',
  'if',
  'vlookup',
  'hlookup',
  'xlookup',
  'pivot table',
  'chart',
  'charts',
  'graph',
  'visualization',
  'format',
  'formatting',
  'number format',
  'currency',
  'percentage',
  'date format',
  'conditional formatting',
  'highlight',
  'color',
  'bold',
  'italic',
  'alignment',
  'merge cells',
  'split cells',
  'wrap text',
  'data validation',
  'dropdown',
  'checkbox',
  'protect',
  'protected range',
  'share',
  'permissions',
  'viewer',
  'commenter',
  'editor',
  'collaborate',
  'real time',
  'version history',
  'revision',
  'undo',
  'redo',
  'import',
  'export',
  'csv',
  'xlsx',
  'download',
  'upload',
];
