export const Trigger = [
  'npm',
  'package',
  'packages',
  'node module',
  'node modules',
  'node package',
  'registry',
  'npm registry',
  'npm install',
  'npm search',
  'install package',
  'yarn add',
  'pnpm add',
  'dependency',
  'dependencies',
  'devdependency',
  'devdependencies',
  'semver',
  'package.json',
  'package version',
  'latest version',
  'npm version',
  'package downloads',
  'weekly downloads',
  'npm downloads',
  'npm stats',
  'package info',
  'package details',
  'package license',
  'open source package',
  'compare packages',
  'vs npm',
  'npm compare',
  'lodash',
  'axios',
  'react',
  'express',
  'typescript',
  'webpack',
  'vite',
  'eslint',
  'prettier',
  'jest',
  'vitest',
  'bundler',
  'transpiler',
  'library',
  'lib',
  'module',
  'bundled',
  'minified',
  'tree shaking',
  'esm',
  'cjs',
  'commonjs',
];
