export const Trigger = [
  'slides',
  'google slides',
  'presentation',
  'presentations',
  'slide',
  'slides deck',
  'deck',
  'create slides',
  'new presentation',
  'edit slides',
  'update slides',
  'delete slides',
  'duplicate slide',
  'copy slide',
  'move slide',
  'reorder slides',
  'layout',
  'layouts',
  'theme',
  'themes',
  'template',
  'templates',
  'design',
  'background',
  'master slide',
  'title slide',
  'section',
  'sections',
  'text',
  'textbox',
  'heading',
  'subtitle',
  'bullet',
  'bullets',
  'numbered list',
  'font',
  'font size',
  'font family',
  'color',
  'alignment',
  'bold',
  'italic',
  'underline',
  'image',
  'images',
  'insert image',
  'video',
  'embed video',
  'youtube video',
  'audio',
  'shape',
  'shapes',
  'icon',
  'icons',
  'chart',
  'charts',
  'table',
  'tables',
  'diagram',
  'smart art',
  'animation',
  'animations',
  'transition',
  'transitions',
  'present',
  'presentation mode',
  'slideshow',
  'speaker notes',
  'notes',
  'pointer',
  'laser pointer',
  'timer',
  'share',
  'sharing',
  'permissions',
  'viewer',
  'commenter',
  'editor',
  'collaborate',
  'real time',
  'comment',
  'comments',
  'suggestion',
  'version history',
  'revision',
  'export',
  'download',
  'pdf',
  'pptx',
  'print',
];
