export const Trigger = [
  'stackoverflow',
  'stack overflow',
  'stack exchange',
  'stackexchange',
  'so answer',
  'so question',
  'so post',
  'error',
  'exception',
  'bug',
  'debug',
  'traceback',
  'typeerror',
  'referenceerror',
  'syntaxerror',
  'undefined is not a function',
  'cannot read property',
  'cannot find module',
  'module not found',
  'segfault',
  'segmentation fault',
  'null pointer',
  'stack trace',
  'runtime error',
  'compile error',
  'build error',
  'how do i',
  'how to',
  'best way to',
  'what is the difference between',
  'when should i use',
  'why is',
  'why does',
  'solution',
  'fix',
  'workaround',
  'issue',
  'problem',
  'question',
  'answered',
  'accepted answer',
  'upvoted',
  'votes',
  'community',
  'developer forum',
  'forum',
  'q&a',
  'code help',
  'code question',
];
