export const Trigger = [
  'gmail',
  'email',
  'emails',
  'mail',
  'inbox',
  'inboxes',
  'message',
  'messages',
  'compose',
  'send',
  'sent',
  'draft',
  'drafts',
  'reply',
  'reply all',
  'forward',
  'cc',
  'bcc',
  'to',
  'from',
  'subject',
  'body',
  'attachment',
  'attachments',
  'attach file',
  'file attachment',
  'image attachment',
  'pdf attachment',
  'link',
  'url',
  'signature',
  'sign off',
  'schedule send',
  'scheduled email',
  'undo send',
  'mark as read',
  'mark as unread',
  'star',
  'starred',
  'important',
  'not important',
  'label',
  'labels',
  'category',
  'categories',
  'primary',
  'social',
  'promotions',
  'updates',
  'forums',
  'spam',
  'junk',
  'trash',
  'bin',
  'delete',
  'archive',
  'mute',
  'snooze',
  'search',
  'filter',
  'rules',
  'blocked',
  'block sender',
  'unsubscribe',
  'thread',
  'conversation',
  'reply thread',
  'email thread',
  'contacts',
  'address book',
  'recipient',
  'recipients',
  'sender',
  'send email',
  'write email',
  'compose email',
  'new mail',
  'check mail',
  'read mail',
  'open email',
  'download attachment',
  'save attachment',
  'preview',
  'print',
  'report spam',
  'phishing',
  'security',
  'verification',
  'otp',
  'two factor',
  '2fa',
  'login alert',
  'account alert',
  'mail settings',
  'auto reply',
  'vacation responder',
  'out of office',
  'forwarding',
  'imap',
  'smtp',
  'pop3',
];
