export const Trigger = [
  'contacts',
  'google contacts',
  'contact',
  'contacts list',
  'address book',
  'person',
  'people',
  'name',
  'first name',
  'last name',
  'full name',
  'nickname',
  'phone',
  'phone number',
  'mobile',
  'mobile number',
  'work phone',
  'home phone',
  'email',
  'email address',
  'primary email',
  'secondary email',
  'company',
  'organization',
  'job title',
  'title',
  'department',
  'manager',
  'assistant',
  'address',
  'home address',
  'work address',
  'city',
  'state',
  'country',
  'postal code',
  'zip code',
  'birthday',
  'anniversary',
  'date of birth',
  'notes',
  'profile',
  'profile picture',
  'photo',
  'avatar',
  'website',
  'url',
  'social',
  'social media',
  'twitter',
  'linkedin',
  'facebook',
  'instagram',
  'group',
  'groups',
  'label',
  'labels',
  'tag',
  'tags',
  'favorite',
  'favorites',
  'starred',
  'import',
  'export',
  'sync',
  'synced',
  'merge',
  'duplicate',
  'duplicates',
  'add contact',
  'create contact',
  'edit contact',
  'update contact',
  'delete contact',
  'remove contact',
  'search contact',
  'find contact',
  'call contact',
  'message contact',
  'share contact',
  'vcard',
  'vcf',
  'directory',
  'global address list',
  'contact info',
  'details',
  'lookup',
  'autocomplete',
  'suggestion',
  'recent contacts',
  'frequent contacts',
];
