export const Trigger = [
  'tasks',
  'google tasks',
  'task',
  'tasks list',
  'to do',
  'todo',
  'to do list',
  'checklist',
  'item',
  'items',
  'create task',
  'new task',
  'add task',
  'edit task',
  'update task',
  'delete task',
  'remove task',
  'complete task',
  'mark complete',
  'mark done',
  'done',
  'pending',
  'incomplete',
  'task title',
  'description',
  'details',
  'notes',
  'due date',
  'deadline',
  'due time',
  'schedule',
  'reminder',
  'reminders',
  'notification',
  'notifications',
  'repeat',
  'recurring',
  'daily',
  'weekly',
  'monthly',
  'yearly',
  'subtask',
  'subtasks',
  'nested task',
  'parent task',
  'child task',
  'task list',
  'lists',
  'create list',
  'delete list',
  'rename list',
  'reorder',
  'priority',
  'high priority',
  'medium priority',
  'low priority',
  'important',
  'star',
  'starred',
  'sort',
  'filter',
  'search',
  'find',
  'archive',
  'archived',
  'restore',
  'clear completed',
  'sync',
  'synced',
  'calendar tasks',
  'integration',
  'google calendar',
  'assign',
  'assigned',
  'assignee',
  'owner',
  'progress',
  'track',
  'tracking',
  'status',
  'not started',
  'in progress',
  'completed',
  'overdue',
  'today',
  'tomorrow',
  'this week',
  'this month',
];
