export const GITHUB_TOOLS = [
  {
    name: 'github_list_repos',
    description: "List the user's GitHub repositories.",
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_issues',
    description: 'Get issues for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_pull_requests',
    description: 'Get pull requests for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_file',
    description: 'Load the contents of a file from a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      filePath: { type: 'string', required: true, description: 'Path to the file inside the repository' },
    },
  },
  {
    name: 'github_get_file_tree',
    description: 'Get the file tree of a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_notifications',
    description: 'Get unread GitHub notifications.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_commits',
    description: 'Get recent commits for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_create_issue',
    description: 'Create a new issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      title: { type: 'string', required: true, description: 'Issue title' },
      body: { type: 'string', required: false, description: 'Issue body in markdown' },
      labels: { type: 'string', required: false, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'github_close_issue',
    description: 'Close an issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_reopen_issue',
    description: 'Reopen a closed issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_comment_on_issue',
    description: 'Comment on a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      body: { type: 'string', required: true, description: 'Comment body in markdown' },
    },
  },
  {
    name: 'github_list_branches',
    description: 'List branches in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_releases',
    description: 'Get recent releases for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      count: { type: 'number', required: false, description: 'Number of releases to fetch (default 5, max 20)' },
    },
  },
  {
    name: 'github_star_repo',
    description: 'Star or unstar a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      action: { type: 'string', required: false, description: 'star (default) or unstar' },
    },
  },
  {
    name: 'github_create_gist',
    description: 'Create a GitHub Gist.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      description: { type: 'string', required: false, description: 'Gist description' },
      filename: { type: 'string', required: true, description: 'Primary file name' },
      content: { type: 'string', required: true, description: 'Primary file content' },
      public: { type: 'boolean', required: false, description: 'Set true to make the gist public' },
    },
  },
  {
    name: 'github_mark_notifications_read',
    description: 'Mark all GitHub notifications as read.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_repo_stats',
    description: 'Get repository statistics such as stars, forks, watchers, and open issues.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_create_pull_request',
    description: 'Create a new pull request in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      title: { type: 'string', required: true, description: 'Pull request title' },
      head: { type: 'string', required: true, description: 'Source branch' },
      base: { type: 'string', required: true, description: 'Target branch' },
      body: { type: 'string', required: false, description: 'Pull request description in markdown' },
      draft: { type: 'boolean', required: false, description: 'Set true to open as a draft pull request' },
    },
  },
  {
    name: 'github_merge_pull_request',
    description: 'Merge a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      merge_method: { type: 'string', required: false, description: 'merge, squash, or rebase' },
      commit_title: { type: 'string', required: false, description: 'Optional custom merge commit title' },
    },
  },
  {
    name: 'github_close_pull_request',
    description: 'Close a pull request without merging it.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_add_labels',
    description: 'Add labels to a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      labels: { type: 'string', required: true, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'github_add_assignees',
    description: 'Assign GitHub users to an issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      assignees: { type: 'string', required: true, description: 'Comma-separated GitHub usernames' },
    },
  },
  {
    name: 'github_trigger_workflow',
    description: 'Trigger a GitHub Actions workflow.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      workflow_id: { type: 'string', required: true, description: 'Workflow file name or numeric ID' },
      ref: { type: 'string', required: false, description: 'Branch or tag to run the workflow on' },
      inputs: { type: 'string', required: false, description: 'JSON string of workflow inputs' },
    },
  },
  {
    name: 'github_get_latest_workflow_run',
    description: 'Get the latest run for a GitHub Actions workflow.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      workflow_id: { type: 'string', required: true, description: 'Workflow file name or numeric ID' },
      branch: { type: 'string', required: false, description: 'Optional branch filter' },
    },
  },
  {
    name: 'github_get_latest_release',
    description: 'Get the latest published release for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_notification_count',
    description: 'Count unread GitHub notifications grouped by repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_load_repo_context',
    description: 'Load a repository tree and selected file contents for deeper code understanding.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      focus_paths: { type: 'string', required: false, description: 'Comma-separated path prefixes to focus on' },
      max_files: { type: 'number', required: false, description: 'Maximum number of files to load (default 20, max 40)' },
    },
  },
  {
    name: 'github_search_code',
    description: 'Search code in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      query: { type: 'string', required: true, description: 'Search query' },
    },
  },
  {
    name: 'github_get_pr_diff',
    description: 'Get the unified diff of a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_review_pr',
    description: 'Post a code review on a GitHub pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      body: { type: 'string', required: true, description: 'Overall review body' },
      verdict: { type: 'string', required: false, description: 'APPROVE, REQUEST_CHANGES, or COMMENT' },
      inline_comments: { type: 'string', required: false, description: 'JSON array of inline comments' },
    },
  },
  {
    name: 'github_get_pr_details',
    description: 'Get detailed pull request metadata.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_pr_checks',
    description: 'Get CI and check status for a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_pr_comments',
    description: 'Load inline review comments for a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_workflow_runs',
    description: 'List recent workflow runs for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      branch: { type: 'string', required: false, description: 'Optional branch filter' },
      event: { type: 'string', required: false, description: 'Optional GitHub event filter' },
      per_page: { type: 'number', required: false, description: 'Maximum number of runs to return (default 20)' },
    },
  },
  {
    name: 'github_get_readme',
    description: 'Fetch the README of a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_issue_details',
    description: 'Get full details of a single GitHub issue.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_update_issue',
    description: 'Update the title, body, state, labels, or assignees of a GitHub issue.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
      title: { type: 'string', required: false, description: 'New title' },
      body: { type: 'string', required: false, description: 'New body in markdown' },
      state: { type: 'string', required: false, description: 'open or closed' },
      labels: { type: 'string', required: false, description: 'Comma-separated label names to set' },
      assignees: { type: 'string', required: false, description: 'Comma-separated GitHub usernames to set' },
    },
  },
  {
    name: 'github_get_contributors',
    description: 'List contributors to a GitHub repository sorted by commit count.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_languages',
    description: 'Get the programming language breakdown (in bytes) for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_topics',
    description: 'Get the topic tags applied to a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_milestones',
    description: 'List milestones for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      state: { type: 'string', required: false, description: 'open (default), closed, or all' },
    },
  },
  {
    name: 'github_create_milestone',
    description: 'Create a milestone in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      title: { type: 'string', required: true, description: 'Milestone title' },
      description: { type: 'string', required: false, description: 'Optional description' },
      due_on: { type: 'string', required: false, description: 'ISO 8601 due date, e.g. 2025-12-31T00:00:00Z' },
    },
  },
  {
    name: 'github_create_branch',
    description: 'Create a new branch in a repository from a given commit SHA.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      branch_name: { type: 'string', required: true, description: 'New branch name' },
      sha: { type: 'string', required: true, description: 'Commit SHA to branch from' },
    },
  },
  {
    name: 'github_delete_branch',
    description: 'Delete a branch from a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      branch_name: { type: 'string', required: true, description: 'Branch to delete' },
    },
  },
  {
    name: 'github_get_forks',
    description: 'List forks of a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_stargazers',
    description: 'List users who have starred a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_collaborators',
    description: 'List collaborators of a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_compare_branches',
    description: 'Compare two branches or commits and show ahead/behind status and changed files.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      base: { type: 'string', required: true, description: 'Base branch or SHA' },
      head: { type: 'string', required: true, description: 'Head branch or SHA to compare' },
    },
  },
  {
    name: 'github_get_gists',
    description: "List the authenticated user's GitHub Gists.",
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_traffic_views',
    description: 'Get view traffic (unique visitors and total views) for a repository over the last 14 days.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_request_reviewers',
    description: 'Request reviewers for a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      reviewers: { type: 'string', required: false, description: 'Comma-separated GitHub usernames' },
      team_reviewers: { type: 'string', required: false, description: 'Comma-separated team slugs' },
    },
  },
  {
    name: 'github_get_pr_files',
    description: 'List the files changed in a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_list_pr_reviews',
    description: 'List all reviews submitted on a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_user_info',
    description: 'Get public profile information for any GitHub user.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username to look up' },
    },
  },

  {
    name: 'github_search_repos',
    description: 'Search GitHub repositories globally by keyword.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      query: { type: 'string', required: true, description: 'Search query (e.g. "react hooks stars:>1000")' },
      count: { type: 'number', required: false, description: 'Max results to return (default 20, max 50)' },
    },
  },
  {
    name: 'github_search_issues',
    description: 'Search issues and pull requests across GitHub.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      query: { type: 'string', required: true, description: 'Search query (e.g. "is:open label:bug repo:owner/repo")' },
      count: { type: 'number', required: false, description: 'Max results to return (default 20, max 50)' },
    },
  },
  {
    name: 'github_get_issue_comments',
    description: 'Get all comments on a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      count: { type: 'number', required: false, description: 'Max comments to return (default 30)' },
    },
  },
  {
    name: 'github_get_commit_details',
    description: 'Get detailed information about a specific commit including file changes and stats.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      sha: { type: 'string', required: true, description: 'Full or abbreviated commit SHA' },
    },
  },
  {
    name: 'github_get_tags',
    description: 'List tags in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      count: { type: 'number', required: false, description: 'Max tags to return (default 20)' },
    },
  },
  {
    name: 'github_create_release',
    description: 'Create a new release in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      tag_name: { type: 'string', required: true, description: 'Tag name for the release (e.g. v1.2.0)' },
      name: { type: 'string', required: false, description: 'Release title (defaults to tag name)' },
      body: { type: 'string', required: false, description: 'Release notes in markdown' },
      draft: { type: 'boolean', required: false, description: 'Set true to create as a draft' },
      prerelease: { type: 'boolean', required: false, description: 'Set true to mark as pre-release' },
      target_commitish: { type: 'string', required: false, description: 'Branch or commit SHA to tag (defaults to default branch)' },
    },
  },
  {
    name: 'github_fork_repo',
    description: 'Fork a GitHub repository into the authenticated user\'s account or a specified organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'Owner of the repository to fork' },
      repo: { type: 'string', required: true, description: 'Repository name to fork' },
      organization: { type: 'string', required: false, description: 'Organization to fork into (omit to fork into personal account)' },
    },
  },
  {
    name: 'github_update_pull_request',
    description: 'Update the title, body, state, or base branch of a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      title: { type: 'string', required: false, description: 'New title' },
      body: { type: 'string', required: false, description: 'New description in markdown' },
      state: { type: 'string', required: false, description: 'open or closed' },
      base: { type: 'string', required: false, description: 'New base branch name' },
    },
  },
  {
    name: 'github_get_labels',
    description: 'List all labels defined in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_create_label',
    description: 'Create a new label in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      name: { type: 'string', required: true, description: 'Label name' },
      color: { type: 'string', required: true, description: 'Hex color without # (e.g. ff0000)' },
      description: { type: 'string', required: false, description: 'Short description of the label' },
    },
  },
  {
    name: 'github_delete_label',
    description: 'Delete a label from a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      name: { type: 'string', required: true, description: 'Exact label name to delete' },
    },
  },
  {
    name: 'github_search_users',
    description: 'Search for GitHub users and organizations.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      query: { type: 'string', required: true, description: 'Search query (e.g. "location:London language:python")' },
      count: { type: 'number', required: false, description: 'Max results to return (default 20, max 50)' },
    },
  },
  {
    name: 'github_get_user_starred',
    description: 'List repositories starred by a GitHub user.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'github_get_file_commits',
    description: 'Get the commit history for a specific file in a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      file_path: { type: 'string', required: true, description: 'Path to the file (e.g. src/index.js)' },
      count: { type: 'number', required: false, description: 'Max commits to return (default 15)' },
    },
  },
  {
    name: 'github_lock_issue',
    description: 'Lock an issue or pull request to prevent further comments.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      lock_reason: { type: 'string', required: false, description: 'off-topic, too heated, resolved, or spam' },
    },
  },
  {
    name: 'github_unlock_issue',
    description: 'Unlock a previously locked issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
    },
  },
  {
    name: 'github_get_deployments',
    description: 'List deployments for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      count: { type: 'number', required: false, description: 'Max deployments to return (default 20)' },
    },
  },
  {
    name: 'github_get_repo_permissions',
    description: 'Get a specific user\'s permission level in a repository (admin, write, read, none).',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      username: { type: 'string', required: true, description: 'GitHub username to check' },
    },
  },
  {
    name: 'github_remove_labels',
    description: 'Remove specific labels from a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      labels: { type: 'string', required: true, description: 'Comma-separated label names to remove' },
    },
  },
  {
    name: 'github_get_pr_requested_reviewers',
    description: 'Get the list of users and teams currently requested to review a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_repo_info',
    description: 'Get full metadata for a GitHub repository including license, visibility, and dates.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_org_repos',
    description: 'List repositories belonging to a GitHub organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
      count: { type: 'number', required: false, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'github_watch_repo',
    description: 'Watch or unwatch a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      action: { type: 'string', required: false, description: 'watch (default) or unwatch' },
    },
  },
  {
    name: 'github_get_user_events',
    description: "Get a GitHub user's recent public activity events.",
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max events to return (default 20)' },
    },
  },
  {
    name: 'github_get_repo_environments',
    description: 'List deployment environments configured for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_list_actions_secrets',
    description: 'List GitHub Actions secret names in a repository (values are never exposed).',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_dependabot_alerts',
    description: 'List Dependabot vulnerability alerts for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      state: { type: 'string', required: false, description: 'open (default), dismissed, or fixed' },
    },
  },
  {
    name: 'github_get_commits_since',
    description: 'Get commits in a repository within a date range.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      since: { type: 'string', required: true, description: 'ISO 8601 start date e.g. 2024-01-01T00:00:00Z' },
      until: { type: 'string', required: false, description: 'ISO 8601 end date (optional)' },
      count: { type: 'number', required: false, description: 'Max commits to return (default 20)' },
    },
  },
  {
    name: 'github_get_branch_protection',
    description: 'Get branch protection rules for a specific branch.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      branch: { type: 'string', required: true, description: 'Branch name e.g. main' },
    },
  },
  {
    name: 'github_get_user_orgs',
    description: "List the public organizations a GitHub user belongs to.",
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
    },
  },
  {
    name: 'github_get_traffic_clones',
    description: 'Get clone traffic stats for a repository over the last 14 days.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_community_profile',
    description: 'Get the community health profile of a repository including readme, license, and contributing guide presence.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_repo_webhooks',
    description: 'List webhooks configured for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_org_members',
    description: 'List public members of a GitHub organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
      count: { type: 'number', required: false, description: 'Max members to return (default 30)' },
    },
  },
  {
    name: 'github_list_org_teams',
    description: 'List teams in a GitHub organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
      count: { type: 'number', required: false, description: 'Max teams to return (default 30)' },
    },
  },
  {
    name: 'github_get_team_members',
    description: 'List members of a specific team within a GitHub organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
      team_slug: { type: 'string', required: true, description: 'Team slug (from github_list_org_teams)' },
      count: { type: 'number', required: false, description: 'Max members to return (default 30)' },
    },
  },
  {
    name: 'github_get_issue_reactions',
    description: 'Get emoji reactions on a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
    },
  },
  {
    name: 'github_get_repo_license',
    description: 'Get the license file and metadata for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_code_frequency',
    description: 'Get weekly addition and deletion counts for a repository (last ~52 weeks).',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_contributor_stats',
    description: 'Get commit, addition, and deletion counts per contributor for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_commit_activity',
    description: 'Get weekly commit counts for a repository over the last year.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_punch_card',
    description: 'Get commit frequency by day of week and hour for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_repo_subscription',
    description: 'Check the authenticated user\'s watch/subscription status for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_user_followers',
    description: 'List followers of a GitHub user.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max followers to return (default 30)' },
    },
  },
  {
    name: 'github_get_user_following',
    description: 'List users that a GitHub user is following.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max following to return (default 30)' },
    },
  },
  {
    name: 'github_get_user_gists',
    description: 'List public gists for a GitHub user.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max gists to return (default 20)' },
    },
  },
  {
    name: 'github_get_gist_details',
    description: 'Get full details and file contents of a specific GitHub Gist.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      gist_id: { type: 'string', required: true, description: 'Gist ID (from github_get_gists or github_get_user_gists)' },
    },
  },
  {
    name: 'github_get_pr_commits',
    description: 'List all commits in a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_commit_statuses',
    description: 'Get CI/CD statuses for a specific commit ref or SHA.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      ref: { type: 'string', required: true, description: 'Commit SHA, branch, or tag' },
    },
  },
  {
    name: 'github_get_repo_pages',
    description: 'Get GitHub Pages configuration and status for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_org_info',
    description: 'Get public profile and metadata for a GitHub organization.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
    },
  },
  {
    name: 'github_search_commits',
    description: 'Search commits across GitHub by message, author, repo, date, etc.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      query: { type: 'string', required: true, description: 'Search query e.g. "fix bug repo:owner/repo author:alice"' },
      count: { type: 'number', required: false, description: 'Max results to return (default 20, max 50)' },
    },
  },
  {
    name: 'github_get_deployment_statuses',
    description: 'Get status history for a specific deployment.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      deployment_id: { type: 'number', required: true, description: 'Deployment ID (from github_get_deployments)' },
    },
  },
  {
    name: 'github_get_repo_invitations',
    description: 'List pending collaboration invitations for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_rate_limit',
    description: 'Check the current GitHub API rate limit status for core, search, and GraphQL.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_list_workflows',
    description: 'List all GitHub Actions workflows in a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_workflow_details',
    description: 'Get metadata for a specific GitHub Actions workflow.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      workflow_id: { type: 'string', required: true, description: 'Workflow file name or numeric ID' },
    },
  },
  {
    name: 'github_get_actions_runners',
    description: 'List self-hosted Actions runners for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_actions_variables',
    description: 'List Actions variables (names and values) for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_actions_cache',
    description: 'List Actions cache entries for a repository including size and last used date.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_team_repos',
    description: 'List repositories a specific team has access to within an org.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
      team_slug: { type: 'string', required: true, description: 'Team slug' },
      count: { type: 'number', required: false, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'github_get_user_repos',
    description: "List public repositories for any GitHub user.",
    category: 'github',
    connectorId: 'github',
    parameters: {
      username: { type: 'string', required: true, description: 'GitHub username' },
      count: { type: 'number', required: false, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'github_get_issue_timeline',
    description: 'Get the full event timeline for a GitHub issue including labels, assignments, renames, and comments.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_get_org_secrets',
    description: 'List org-level GitHub Actions secret names (values are never exposed).',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
    },
  },
  {
    name: 'github_get_single_comment',
    description: 'Get a single issue or PR comment by its ID.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      comment_id: { type: 'number', required: true, description: 'Comment ID' },
    },
  },
  {
    name: 'github_get_security_advisories',
    description: 'List published security advisories for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_pr_review_details',
    description: 'Get the full details of a single PR review by its ID.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      review_id: { type: 'number', required: true, description: 'Review ID (from github_list_pr_reviews)' },
    },
  },
  {
    name: 'github_get_org_variables',
    description: 'List org-level GitHub Actions variables.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      org: { type: 'string', required: true, description: 'GitHub organization name' },
    },
  },
  {
    name: 'github_get_repo_autolinks',
    description: 'List autolink references configured for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_check_run_details',
    description: 'Get full details of a specific CI check run including status, conclusion, and output summary.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      check_run_id: { type: 'number', required: true, description: 'Check run ID (from github_get_pr_checks)' },
    },
  },
];

export default GITHUB_TOOLS;
