export const GITHUB_TOOLS = [
  {
    name: 'github_list_repos',
    description: "List the user's GitHub repositories.",
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_issues',
    description: 'Get issues for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_pull_requests',
    description: 'Get pull requests for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_file',
    description: 'Load the contents of a file from a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      filePath: { type: 'string', required: true, description: 'Path to the file inside the repository' },
    },
  },
  {
    name: 'github_get_file_tree',
    description: 'Get the file tree of a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_notifications',
    description: 'Get unread GitHub notifications.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_commits',
    description: 'Get recent commits for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_create_issue',
    description: 'Create a new issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      title: { type: 'string', required: true, description: 'Issue title' },
      body: { type: 'string', required: false, description: 'Issue body in markdown' },
      labels: { type: 'string', required: false, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'github_close_issue',
    description: 'Close an issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_reopen_issue',
    description: 'Reopen a closed issue in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue number' },
    },
  },
  {
    name: 'github_comment_on_issue',
    description: 'Comment on a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      body: { type: 'string', required: true, description: 'Comment body in markdown' },
    },
  },
  {
    name: 'github_list_branches',
    description: 'List branches in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_releases',
    description: 'Get recent releases for a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      count: { type: 'number', required: false, description: 'Number of releases to fetch (default 5, max 20)' },
    },
  },
  {
    name: 'github_star_repo',
    description: 'Star or unstar a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      action: { type: 'string', required: false, description: 'star (default) or unstar' },
    },
  },
  {
    name: 'github_create_gist',
    description: 'Create a GitHub Gist.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      description: { type: 'string', required: false, description: 'Gist description' },
      filename: { type: 'string', required: true, description: 'Primary file name' },
      content: { type: 'string', required: true, description: 'Primary file content' },
      public: { type: 'boolean', required: false, description: 'Set true to make the gist public' },
    },
  },
  {
    name: 'github_mark_notifications_read',
    description: 'Mark all GitHub notifications as read.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_get_repo_stats',
    description: 'Get repository statistics such as stars, forks, watchers, and open issues.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_create_pull_request',
    description: 'Create a new pull request in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      title: { type: 'string', required: true, description: 'Pull request title' },
      head: { type: 'string', required: true, description: 'Source branch' },
      base: { type: 'string', required: true, description: 'Target branch' },
      body: { type: 'string', required: false, description: 'Pull request description in markdown' },
      draft: { type: 'boolean', required: false, description: 'Set true to open as a draft pull request' },
    },
  },
  {
    name: 'github_merge_pull_request',
    description: 'Merge a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      merge_method: { type: 'string', required: false, description: 'merge, squash, or rebase' },
      commit_title: { type: 'string', required: false, description: 'Optional custom merge commit title' },
    },
  },
  {
    name: 'github_close_pull_request',
    description: 'Close a pull request without merging it.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_add_labels',
    description: 'Add labels to a GitHub issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      labels: { type: 'string', required: true, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'github_add_assignees',
    description: 'Assign GitHub users to an issue or pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      issue_number: { type: 'number', required: true, description: 'Issue or pull request number' },
      assignees: { type: 'string', required: true, description: 'Comma-separated GitHub usernames' },
    },
  },
  {
    name: 'github_trigger_workflow',
    description: 'Trigger a GitHub Actions workflow.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      workflow_id: { type: 'string', required: true, description: 'Workflow file name or numeric ID' },
      ref: { type: 'string', required: false, description: 'Branch or tag to run the workflow on' },
      inputs: { type: 'string', required: false, description: 'JSON string of workflow inputs' },
    },
  },
  {
    name: 'github_get_latest_workflow_run',
    description: 'Get the latest run for a GitHub Actions workflow.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      workflow_id: { type: 'string', required: true, description: 'Workflow file name or numeric ID' },
      branch: { type: 'string', required: false, description: 'Optional branch filter' },
    },
  },
  {
    name: 'github_get_latest_release',
    description: 'Get the latest published release for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub username or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
    },
  },
  {
    name: 'github_get_notification_count',
    description: 'Count unread GitHub notifications grouped by repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {},
  },
  {
    name: 'github_load_repo_context',
    description: 'Load a repository tree and selected file contents for deeper code understanding.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      focus_paths: { type: 'string', required: false, description: 'Comma-separated path prefixes to focus on' },
      max_files: { type: 'number', required: false, description: 'Maximum number of files to load (default 20, max 40)' },
    },
  },
  {
    name: 'github_search_code',
    description: 'Search code in a GitHub repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      query: { type: 'string', required: true, description: 'Search query' },
    },
  },
  {
    name: 'github_get_pr_diff',
    description: 'Get the unified diff of a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_review_pr',
    description: 'Post a code review on a GitHub pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
      body: { type: 'string', required: true, description: 'Overall review body' },
      verdict: { type: 'string', required: false, description: 'APPROVE, REQUEST_CHANGES, or COMMENT' },
      inline_comments: { type: 'string', required: false, description: 'JSON array of inline comments' },
    },
  },
  {
    name: 'github_get_pr_details',
    description: 'Get detailed pull request metadata.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_pr_checks',
    description: 'Get CI and check status for a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_pr_comments',
    description: 'Load inline review comments for a pull request.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      pr_number: { type: 'number', required: true, description: 'Pull request number' },
    },
  },
  {
    name: 'github_get_workflow_runs',
    description: 'List recent workflow runs for a repository.',
    category: 'github',
    connectorId: 'github',
    parameters: {
      owner: { type: 'string', required: true, description: 'GitHub owner or organization' },
      repo: { type: 'string', required: true, description: 'Repository name' },
      branch: { type: 'string', required: false, description: 'Optional branch filter' },
      event: { type: 'string', required: false, description: 'Optional GitHub event filter' },
      per_page: { type: 'number', required: false, description: 'Maximum number of runs to return (default 20)' },
    },
  },
];

export default GITHUB_TOOLS;
