export const Trigger = [
  'stripe',
  'app',
  'payments',
  'payment',
  'charge',
  'charges',
  'customers',
  'customer',
  'subscriptions',
  'subscription',
  'invoices',
  'invoice',
  'billing',
  'revenue',
  'balance',
  'payout',
  'payouts',
  'transfer',
  'transfers',
  'refund',
  'refunds',
  'dispute',
  'disputes',
  'checkout',
  'checkout session',
  'session',
  'payment intent',
  'payment intents',
  'setup intent',
  'setup intents',
  'product',
  'products',
  'price',
  'prices',
  'plan',
  'plans',
  'usage',
  'metered billing',
  'recurring billing',
  'one time payment',
  'webhooks',
  'webhook',
  'events',
  'event',
  'api',
  'sdk',
  'token',
  'keys',
  'secret key',
  'publishable key',
  'connect',
  'account',
  'accounts',
  'onboarding',
  'identity',
  'verification',
  'tax',
  'tax rates',
  'coupon',
  'coupons',
  'discount',
  'discounts',
  'promotion',
  'promo code',
  'receipts',
  'receipt',
  'email receipt',
  'statement',
  'reporting',
  'reports',
  'analytics',
  'dashboard',
  'logs',
  'log',
  'errors',
  'status',
  'uptime',
  'test mode',
  'live mode',
  'sandbox',
  'environment',
  'settings',
  'configuration',
  'billing portal',
  'customer portal',
  'cancel subscription',
  'update subscription',
  'create subscription',
  'create customer',
  'update customer',
  'delete customer',
  'create charge',
  'capture payment',
  'confirm payment',
  'payments',
  'billing',
  'revenue',
  'subscriptions',
  'invoices',
  'payouts',
  'refunds',
  'financial reports',
];
