function apiKeyField(placeholder) {
  return [
    {
      key: 'apiKey',
      type: 'password',
      placeholder,
      required: true,
      minLength: 8,
    },
  ];
}

function localModelFields(defaultEndpoint, modelIdLabel, modelPlaceholder) {
  return [
    {
      key: 'endpoint',
      label: 'Server URL',
      type: 'text',
      placeholder: defaultEndpoint,
      defaultValue: defaultEndpoint,
      required: true,
      minLength: 10,
    },
    {
      key: 'modelId',
      label: modelIdLabel,
      type: 'text',
      placeholder: modelPlaceholder,
      required: false,
      minLength: 2,
    },
  ];
}

export const PROVIDERS = [
  {
    id: 'anthropic',
    label: 'Claude',
    company: 'Anthropic',
    caption: 'API key',
    color: '#cc785c',
    iconPath: '../../../Assets/Icons/Claude.png',
    iconSize: '36px',
    fallback: 'C',
    fields: apiKeyField('sk-ant-api03-...'),
  },
  {
    id: 'openai',
    label: 'ChatGPT',
    company: 'OpenAI',
    caption: 'API key',
    color: '#10a37f',
    iconPath: '../../../Assets/Icons/ChatGPT.png',
    iconSize: '36px',
    fallback: 'GPT',
    fields: apiKeyField('sk-proj-...'),
  },
  {
    id: 'google',
    label: 'Gemini',
    company: 'Google',
    caption: 'API key',
    color: '#4285f4',
    iconPath: '../../../Assets/Icons/Gemini.png',
    iconSize: '40px',
    fallback: 'G',
    fields: apiKeyField('AIza...'),
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    company: '',
    caption: 'API key',
    color: '#9b59b6',
    iconPath: '../../../Assets/Icons/OpenRouter.png',
    iconFrame: 'solid',
    iconSize: '32px',
    fallback: 'OR',
    fields: apiKeyField('sk-or-v1-...'),
  },
  {
    id: 'mistral',
    label: 'Mistral',
    company: '',
    caption: 'API key',
    color: '#d17c48',
    iconPath: '../../../Assets/Icons/Mistral.png',
    iconSize: '38px',
    fallback: 'MI',
    fields: apiKeyField('mistral-...'),
  },
  {
    id: 'nvidia',
    label: 'NVIDIA',
    company: 'NVIDIA',
    caption: 'API key',
    color: '#76b900',
    iconPath: '../../../Assets/Icons/Nvidia.png',
    iconSize: '42px',
    fallback: 'NV',
    fields: apiKeyField('nvapi-...'),
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    company: 'DeepSeek',
    caption: 'API key',
    color: '#4f7cff',
    iconPath: '../../../Assets/Icons/Deepseek.png',
    iconSize: '34px',
    fallback: 'DS',
    fields: apiKeyField('sk-...'),
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    company: 'MiniMax',
    caption: 'API key',
    color: '#ef6b3d',
    iconPath: '../../../Assets/Icons/MiniMax.png',
    iconFrame: 'soft',
    iconSize: '18px',
    fallback: 'MM',
    fields: apiKeyField('Paste your API key'),
  },
  {
    id: 'ollama',
    label: 'Ollama',
    company: 'Local AI',
    caption: 'Local server',
    color: '#111827',
    iconPath: '../../../Assets/Icons/Ollama.png',
    iconFrame: 'soft',
    iconSize: '30px',
    fallback: 'OL',
    hint: 'Run Ollama and Joanium will detect the local models it exposes. You can optionally set a preferred model below.',
    fields: localModelFields('http://127.0.0.1:11434', 'Preferred model (optional)', 'llama3.2'),
  },
  {
    id: 'lmstudio',
    label: 'LM Studio',
    company: 'Local AI',
    caption: 'Local server',
    color: '#5b6cff',
    iconPath: '../../../Assets/Icons/LmStudio.png',
    iconFrame: 'soft',
    iconSize: '30px',
    fallback: 'LM',
    hint: 'Run the LM Studio local server and Joanium will detect the loaded models. You can optionally set a preferred model below.',
    fields: localModelFields(
      'http://127.0.0.1:1234',
      'Preferred model (optional)',
      'qwen2.5-coder-7b-instruct',
    ),
  },
];

export const PROVIDERS_BY_ID = Object.fromEntries(
  PROVIDERS.map((provider) => [provider.id, provider]),
);
