export const Trigger = [
  'forms',
  'google forms',
  'form',
  'forms builder',
  'survey',
  'surveys',
  'quiz',
  'quizzes',
  'questionnaire',
  'poll',
  'polls',
  'create form',
  'new form',
  'edit form',
  'update form',
  'delete form',
  'duplicate form',
  'copy form',
  'template',
  'templates',
  'title',
  'description',
  'question',
  'questions',
  'add question',
  'edit question',
  'delete question',
  'required',
  'optional',
  'short answer',
  'paragraph',
  'multiple choice',
  'checkboxes',
  'dropdown',
  'file upload',
  'linear scale',
  'rating',
  'grid',
  'multiple choice grid',
  'checkbox grid',
  'date',
  'time',
  'section',
  'sections',
  'add section',
  'page break',
  'logic',
  'branching',
  'skip logic',
  'go to section',
  'validation',
  'response validation',
  'limit',
  'response limit',
  'collect email',
  'email collection',
  'anonymous',
  'responses',
  'response',
  'submit',
  'submission',
  'view responses',
  'summary',
  'individual responses',
  'download responses',
  'export',
  'csv',
  'xlsx',
  'link',
  'form link',
  'share',
  'sharing',
  'permissions',
  'public',
  'private',
  'restricted',
  'theme',
  'customize',
  'color',
  'font',
  'header image',
  'preview',
  'send',
  'email',
  'embed',
  'iframe',
  'confirmation message',
  'edit after submit',
  'limit to 1 response',
  'shuffle questions',
  'shuffle options',
  'auto grade',
  'points',
  'answer key',
  'quiz settings',
  'feedback',
  'notifications',
  'response receipt',
];
