export const Trigger = [
  'password',
  'passwords',
  'generate password',
  'strong password',
  'secure password',
  'random password',
  'passcode',
  'pin',
  'otp',
  'one time password',
  '2fa',
  'two factor',
  'authentication',
  'security',
  'secure',
  'encryption',
  'hash',
  'hashing',
  'salt',
  'credential',
  'credentials',
  'login',
  'signin',
  'signup',
  'account',
  'access',
  'reset password',
  'change password',
  'forgot password',
  'password manager',
  'vault',
  'keychain',
  'secret',
  'token',
  'api key',
  'private key',
  'public key',
];
