export const Trigger = [
  'quote',
  'quotes',
  'quotation',
  'quotations',
  'famous quote',
  'inspiration',
  'motivational',
  'motivation',
  'inspire',
  'inspiring',
  'wisdom',
  'life quote',
  'love quote',
  'success quote',
  'philosophy',
  'philosophical',
  'thought',
  'thoughts',
  'saying',
  'proverb',
  'proverbs',
  'author',
  'authors',
  'famous people',
  'lines',
  'captions',
  'caption',
  'instagram caption',
  'deep',
  'meaningful',
  'positive',
  'mindset',
  'growth',
  'self help',
  'reflection',
  'daily quote',
];
